### ISSUE TITLE
Recursion error with post function

### ISSUE THREAD

**Issue by Jhamali** [PalisadoesFoundation/mdl#20]
Bug report

### Input Code

```python
def your_code():
    ./bin/tools/test_installation.py mdl --post
```

### Infoset Configuration (etc/config.yaml)

```yaml
{
main:
  bind_port: 3000
  db_hostname: localhost
  db_name: mdl_ng
  db_password: password
  db_username: root
  mdl_server_url: /mdl/api/v1
  infoset_server_https: false
  infoset_server_name: 0.0.0.0
  infoset_server_port: 6000
  infoset_server_uri: /infoset/api/v1
  interval: 60
  listen_address: 0.0.0.0
  log_directory: /home/proxima/Dev/github/mdl/log
  log_level: debug
  memcached_hostname: localhost
  memcached_port: 11211
  sqlalchemy_max_overflow: 10
  sqlalchemy_pool_size: 10
}
```

### Expected Behavior

mdl starts

### Current Behavior

RecursionError: maximum recursion depth exceeded while calling a Python object

### Context

Trying to start mdl for testing

### Your Environment

| software         | version(s)
| ---------------- | -------
|infoset           | 2.1.1
| mdl               |  1
| node             | 4.2.6
| npm              | 3.5.2
| Operating System |Ubuntu 16 
```
